name: Run Tests on Pull Request

on:
  pull_request:
    branches:
      - main  # Replace with the default branch name if it's not 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      run: |
        git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY repo
        cd repo

    - name: Set up Python
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip python3-venv
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip

    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Install test dependencies
      run: |
        source venv/bin/activate
        pip install -r requirements-tests.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest --maxfail=5 --disable-warnings -v
