name: Run Tests on Pull Request

on:
  pull_request:
    branches:
      - main  # Replace with your default branch if it's not 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Replace with your Python version if different

    # Install general dependencies
    - name: Install general dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Install test-specific dependencies
    - name: Install test dependencies
      run: |
        pip install -r requirements-tests.txt

    # Run the tests
    - name: Run pytest
      run: pytest --maxfail=5 --disable-warnings -v
